// This file is auto-generated by libs/boxes/generators/react.js. Do not modify manually.

import type { DetailedHTMLProps, HTMLAttributes } from 'react';

type BaseReactProps<Element extends HTMLElement> = DetailedHTMLProps<
  HTMLAttributes<Element>,
  Element
>;

type ComponentElementMap = {
  'boxes-calendar-picker': import('../calendar-picker').CalendarPickerEl;
  'boxes-checkbox': import('../checkbox').CheckboxEl;
  'boxes-combobox': import('../combobox').ComboboxEl;
  'boxes-multi-select': import('../multi-select').MultiSelectEl;
};

type ComponentPropertyMap = {
  'boxes-calendar-picker': {
    'disabled': import('../calendar-picker').CalendarPickerEl['disabled'];
    'fullwidth': import('../calendar-picker').CalendarPickerEl['fullwidth'];
    'name': import('../calendar-picker').CalendarPickerEl['name'];
    'placeholder': import('../calendar-picker').CalendarPickerEl['placeholder'];
    'required': import('../calendar-picker').CalendarPickerEl['required'];
    'value': import('../calendar-picker').CalendarPickerEl['value'];
  };
  'boxes-checkbox': {
    'checked': import('../checkbox').CheckboxEl['checked'];
    'disabled': import('../checkbox').CheckboxEl['disabled'];
    'name': import('../checkbox').CheckboxEl['name'];
    'required': import('../checkbox').CheckboxEl['required'];
    'value': import('../checkbox').CheckboxEl['value'];
  };
  'boxes-combobox': {
    'disabled': import('../combobox').ComboboxEl['disabled'];
    'fullwidth': import('../combobox').ComboboxEl['fullwidth'];
    'name': import('../combobox').ComboboxEl['name'];
    'required': import('../combobox').ComboboxEl['required'];
    'value': import('../combobox').ComboboxEl['value'];
  };
  'boxes-multi-select': {
    'disabled': import('../multi-select').MultiSelectEl['disabled'];
    'fullwidth': import('../multi-select').MultiSelectEl['fullwidth'];
    'name': import('../multi-select').MultiSelectEl['name'];
    'required': import('../multi-select').MultiSelectEl['required'];
    'selectedValues': import('../multi-select').MultiSelectEl['selectedValues'];
    'value': import('../multi-select').MultiSelectEl['value'];
  };
};

type ComponentEventMap = {
  'boxes-calendar-picker': {
    'onchange'?: (event: Event) => void;
    'onChange'?: (event: Event) => void;
  };
  'boxes-checkbox': {
    'onchange'?: (event: Event) => void;
    'onChange'?: (event: Event) => void;
    'oninput'?: (event: Event) => void;
    'onInput'?: (event: Event) => void;
  };
  'boxes-combobox': {
    'onchange'?: (event: Event) => void;
    'onChange'?: (event: Event) => void;
    'oninput'?: (event: Event) => void;
    'onInput'?: (event: Event) => void;
  };
  'boxes-multi-select': {
    'onchange'?: (event: Event) => void;
    'onChange'?: (event: Event) => void;
    'oninput'?: (event: Event) => void;
    'onInput'?: (event: Event) => void;
  };
};

type ComponentTagName = keyof ComponentElementMap;
type ComponentProps<Tag extends ComponentTagName> = Omit<
  BaseReactProps<ComponentElementMap[Tag]>,
  keyof ComponentPropertyMap[Tag] | keyof ComponentEventMap[Tag]
> &
  Partial<ComponentPropertyMap[Tag]> &
  Partial<ComponentEventMap[Tag]>;

declare module 'react/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'boxes-calendar-picker': ComponentProps<'boxes-calendar-picker'>;
      'boxes-checkbox': ComponentProps<'boxes-checkbox'>;
      'boxes-combobox': ComponentProps<'boxes-combobox'>;
      'boxes-multi-select': ComponentProps<'boxes-multi-select'>;
    }
  }
}
