// This file is auto-generated by libs/boxes/generators/react.js. Do not modify manually.

import type { DetailedHTMLProps, HTMLAttributes } from 'react';

type BaseReactProps<Element extends HTMLElement> = DetailedHTMLProps<
  HTMLAttributes<Element>,
  Element
>;

type ComponentElementMap = {
  'boxes-calendar-picker': import('../calendar-picker').CalendarPickerEl;
  'boxes-checkbox': import('../checkbox').CheckboxEl;
  'boxes-combo-box': import('../combo-box').ComboBoxEl;
  'boxes-select-multiple': import('../select-multiple').SelectMultipleEl;
};

type ComponentPropertyMap = {
  'boxes-calendar-picker': {
    'disabled': import('../calendar-picker').CalendarPickerEl['disabled'];
    'fullwidth': import('../calendar-picker').CalendarPickerEl['fullwidth'];
    'name': import('../calendar-picker').CalendarPickerEl['name'];
    'placeholder': import('../calendar-picker').CalendarPickerEl['placeholder'];
    'required': import('../calendar-picker').CalendarPickerEl['required'];
    'value': import('../calendar-picker').CalendarPickerEl['value'];
  };
  'boxes-checkbox': {
    'checked': import('../checkbox').CheckboxEl['checked'];
    'disabled': import('../checkbox').CheckboxEl['disabled'];
    'name': import('../checkbox').CheckboxEl['name'];
    'required': import('../checkbox').CheckboxEl['required'];
    'value': import('../checkbox').CheckboxEl['value'];
  };
  'boxes-combo-box': {
    'disabled': import('../combo-box').ComboBoxEl['disabled'];
    'fullwidth': import('../combo-box').ComboBoxEl['fullwidth'];
    'name': import('../combo-box').ComboBoxEl['name'];
    'required': import('../combo-box').ComboBoxEl['required'];
    'value': import('../combo-box').ComboBoxEl['value'];
  };
  'boxes-select-multiple': {
    'disabled': import('../select-multiple').SelectMultipleEl['disabled'];
    'fullwidth': import('../select-multiple').SelectMultipleEl['fullwidth'];
    'name': import('../select-multiple').SelectMultipleEl['name'];
    'required': import('../select-multiple').SelectMultipleEl['required'];
    'selectedValues': import('../select-multiple').SelectMultipleEl['selectedValues'];
    'value': import('../select-multiple').SelectMultipleEl['value'];
  };
};

type ComponentEventMap = {
  'boxes-calendar-picker': {
    'onchange'?: (event: Event) => void;
    'onChange'?: (event: Event) => void;
  };
  'boxes-checkbox': {
    'onchange'?: (event: Event) => void;
    'onChange'?: (event: Event) => void;
    'oninput'?: (event: Event) => void;
    'onInput'?: (event: Event) => void;
  };
  'boxes-combo-box': {
    'onchange'?: (event: Event) => void;
    'onChange'?: (event: Event) => void;
    'oninput'?: (event: Event) => void;
    'onInput'?: (event: Event) => void;
  };
  'boxes-select-multiple': {
    'onchange'?: (event: Event) => void;
    'onChange'?: (event: Event) => void;
    'oninput'?: (event: Event) => void;
    'onInput'?: (event: Event) => void;
  };
};

type ComponentTagName = keyof ComponentElementMap;
type ComponentProps<Tag extends ComponentTagName> = Omit<
  BaseReactProps<ComponentElementMap[Tag]>,
  keyof ComponentPropertyMap[Tag] | keyof ComponentEventMap[Tag]
> &
  Partial<ComponentPropertyMap[Tag]> &
  Partial<ComponentEventMap[Tag]>;

declare module 'react/jsx-runtime' {
  namespace JSX {
    interface IntrinsicElements {
      'boxes-calendar-picker': ComponentProps<'boxes-calendar-picker'>;
      'boxes-checkbox': ComponentProps<'boxes-checkbox'>;
      'boxes-combo-box': ComponentProps<'boxes-combo-box'>;
      'boxes-select-multiple': ComponentProps<'boxes-select-multiple'>;
    }
  }
}
