import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { collectComponentMetadata } from './component-metadata.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const OUTPUT_FILE = path.resolve(__dirname, '../src/types/react.d.ts');

async function main() {
  const { components } = await collectComponentMetadata();
  const content = buildTypingsFile(components);

  await fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true });
  await fs.writeFile(OUTPUT_FILE, content, 'utf8');

  console.log(`Generated React typings for ${components.length} components.`);
}

function buildTypingsFile(components) {
  const lines = [
    '// This file is auto-generated by libs/boxes/generators/react.js. Do not modify manually.',
    '',
    "import type { DetailedHTMLProps, HTMLAttributes } from 'react';",
    '',
    'type BaseReactProps<Element extends HTMLElement> = DetailedHTMLProps<',
    '  HTMLAttributes<Element>,',
    '  Element',
    '>;',
    '',
    'type ComponentElementMap = {',
  ];

  for (const component of components) {
    lines.push(
      `  '${component.tagName}': import('${component.importPath}').${component.className};`,
    );
  }

  lines.push('};', '', 'type ComponentPropertyMap = {');

  for (const component of components) {
    lines.push(`  '${component.tagName}': {`);

    for (const property of component.reactProperties) {
      lines.push(
        `    '${property.name}': import('${component.importPath}').${component.className}['${property.memberName}'];`,
      );
    }

    lines.push('  };');
  }

  lines.push('};', '', 'type ComponentEventMap = {');

  for (const component of components) {
    lines.push(`  '${component.tagName}': {`);

    for (const event of component.events) {
      for (const eventPropName of getEventPropNames(event.name)) {
        lines.push(`    '${eventPropName}'?: (event: ${event.typeText}) => void;`);
      }
    }

    lines.push('  };');
  }

  lines.push(
    '};',
    '',
    'type ComponentTagName = keyof ComponentElementMap;',
    'type ComponentProps<Tag extends ComponentTagName> = Omit<',
    '  BaseReactProps<ComponentElementMap[Tag]>,',
    '  keyof ComponentPropertyMap[Tag] | keyof ComponentEventMap[Tag]',
    '> &',
    '  Partial<ComponentPropertyMap[Tag]> &',
    '  Partial<ComponentEventMap[Tag]>;',
    '',
    "declare module 'react/jsx-runtime' {",
    '  namespace JSX {',
    '    interface IntrinsicElements {',
  );

  for (const component of components) {
    lines.push(
      `      '${component.tagName}': ComponentProps<'${component.tagName}'>;`,
    );
  }

  lines.push('    }', '  }', '}', '');

  return lines.join('\n');
}

function getEventPropNames(eventName) {
  const pascalCaseName = eventName
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((segment) => segment[0].toUpperCase() + segment.slice(1))
    .join('');

  return Array.from(
    new Set([
      `on${eventName}`,
      pascalCaseName ? `on${pascalCaseName}` : `on${eventName}`,
    ]),
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
